import type { HistoryDTO } from "../types/dashboard.types";

export const jeonseDummy: HistoryDTO = {
  surveyDto: {
    surveyId: 8,
    workPlaceAddress: "경기도 과천시 과천대로12길 117 아이티센타워 E동",
    jeonseMin: 10000,
    jeonseMax: 20000,
    monthlyMin: null,
    monthlyMax: null,
    depositMin: null,
    depositMax: null,
    preferenceLargeStore: "MIDDLE",
    preferenceHospital: "MIDDLE",
    preferenceSubway: "HIGH",
    preferenceLibrary: "LOW",
    surveySelectedDistrictList: [
      {
        id: 19,
        districtName: "관악구",
      },
      {
        id: 18,
        districtName: "송파구",
      },
      {
        id: 20,
        districtName: "중랑구",
      },
    ],
    submittedAt: "2026-05-13",
  },
  rankings: [
    {
      ranking: 1,
      dongCode: 1171010500,
      districtName: "송파구",
      dongName: "석촌동",
      commuteTime: 71,
    },
    {
      ranking: 2,
      dongCode: 1162010100,
      districtName: "관악구",
      dongName: "봉천동",
      commuteTime: 43,
    },
    {
      ranking: 3,
      dongCode: 1126010200,
      districtName: "중랑구",
      dongName: "상봉동",
      commuteTime: 74,
    },
    {
      ranking: 4,
      dongCode: 1171010100,
      districtName: "송파구",
      dongName: "잠실동",
      commuteTime: 54,
    },
    {
      ranking: 5,
      dongCode: 1162010200,
      districtName: "관악구",
      dongName: "신림동",
      commuteTime: 57,
    },
    {
      ranking: 6,
      dongCode: 1171010600,
      districtName: "송파구",
      dongName: "삼전동",
      commuteTime: 68,
    },
    {
      ranking: 7,
      dongCode: 1171010700,
      districtName: "송파구",
      dongName: "가락동",
      commuteTime: 73,
    },
    {
      ranking: 8,
      dongCode: 1126010100,
      districtName: "중랑구",
      dongName: "면목동",
      commuteTime: 68,
    },
    {
      ranking: 9,
      dongCode: 1126010300,
      districtName: "중랑구",
      dongName: "중화동",
      commuteTime: 78,
    },
    {
      ranking: 10,
      dongCode: 1171010400,
      districtName: "송파구",
      dongName: "송파동",
      commuteTime: 69,
    },
  ],
};

export const wolseDummy: HistoryDTO = {
  surveyDto: {
    surveyId: 8,
    workPlaceAddress: "경기도 과천시 과천대로12길 117 아이티센타워 E동",
    jeonseMin: null,
    jeonseMax: null,
    monthlyMin: 30,
    monthlyMax: 100,
    depositMin: 5000,
    depositMax: 10000,
    preferenceLargeStore: "MIDDLE",
    preferenceHospital: "MIDDLE",
    preferenceSubway: "HIGH",
    preferenceLibrary: "LOW",
    surveySelectedDistrictList: [
      {
        id: 19,
        districtName: "관악구",
      },
      {
        id: 18,
        districtName: "송파구",
      },
      {
        id: 20,
        districtName: "중랑구",
      },
    ],
    submittedAt: "2026-05-13",
  },
  rankings: [
    {
      ranking: 1,
      dongCode: 1171010500,
      districtName: "송파구",
      dongName: "석촌동",
      commuteTime: 71,
    },
    {
      ranking: 2,
      dongCode: 1162010100,
      districtName: "관악구",
      dongName: "봉천동",
      commuteTime: 43,
    },
    {
      ranking: 3,
      dongCode: 1126010200,
      districtName: "중랑구",
      dongName: "상봉동",
      commuteTime: 74,
    },
    {
      ranking: 4,
      dongCode: 1171010100,
      districtName: "송파구",
      dongName: "잠실동",
      commuteTime: 54,
    },
    {
      ranking: 5,
      dongCode: 1162010200,
      districtName: "관악구",
      dongName: "신림동",
      commuteTime: 57,
    },
    {
      ranking: 6,
      dongCode: 1171010600,
      districtName: "송파구",
      dongName: "삼전동",
      commuteTime: 68,
    },
    {
      ranking: 7,
      dongCode: 1171010700,
      districtName: "송파구",
      dongName: "가락동",
      commuteTime: 73,
    },
    {
      ranking: 8,
      dongCode: 1126010100,
      districtName: "중랑구",
      dongName: "면목동",
      commuteTime: 68,
    },
    {
      ranking: 9,
      dongCode: 1126010300,
      districtName: "중랑구",
      dongName: "중화동",
      commuteTime: 78,
    },
    {
      ranking: 10,
      dongCode: 1171010400,
      districtName: "송파구",
      dongName: "송파동",
      commuteTime: 69,
    },
  ],
};
